import os

INSTANCE_ID = os.getenv("INSTANCE_ID")
API_TOKEN = os.getenv("API_TOKEN")
CLIENT_TOKEN = os.getenv("CLIENT_TOKEN")

AZURE_FILE_ACCOUNT_NAME = os.getenv("AZURE_FILE_ACCOUNT_NAME")
AZURE_FILE_ACCOUNT_KEY = os.getenv("AZURE_FILE_ACCOUNT_KEY")
AZURE_FILE_SHARE_NAME = os.getenv("AZURE_FILE_SHARE_NAME")

GOOGLE_CREDS_JSON = os.getenv("GOOGLE_CREDS_JSON")
GOOGLE_CREDS_PATH = "/etc/secrets/GOOGLE_CREDS_JSON"
GOOGLE_SHEETS_PATH = "/etc/secrets/acc_servico"

INFOSIMPLES_TOKEN = os.getenv("INFOSIMPLES_TOKEN")
CERTIFICADO_BASE64 = os.getenv("CERTIFICADO_BASE64")
CERTIFICADO_SENHA = os.getenv("CERTIFICADO_SENHA")
CHAVE_AES = os.getenv("CHAVE_AES")
