import os

ZAPI_INSTANCE_ID = os.getenv("ZAPI_INSTANCE_ID")
ZAPI_API_TOKEN = os.getenv("ZAPI_API_TOKEN")
ZAPI_CLIENT_TOKEN = os.getenv("ZAPI_CLIENT_TOKEN")

DCAN_TOKEN_KEY = os.getenv("DCAN_TOKEN_KEY")

AZURE_FILE_ACCOUNT_NAME = os.getenv("AZURE_FILE_ACCOUNT_NAME")
AZURE_FILE_ACCOUNT_KEY = os.getenv("AZURE_FILE_ACCOUNT_KEY")
AZURE_FILE_SHARE_NAME = os.getenv("AZURE_FILE_SHARE_NAME")

GOOGLE_CREDS_JSON = os.getenv("GOOGLE_CREDS_JSON")
GOOGLE_CREDS_PATH = "/etc/secrets/GOOGLE_CREDS_JSON"
GOOGLE_SHEETS_PATH = "/etc/secrets/acc_servico"

mapa_setores = {
    "comercial": os.getenv("SETOR_COMERCIAL", "DEFAULT_COMERCIAL"),
    "faturamento": os.getenv("SETOR_FATURAMENTO", "DEFAULT_FATURAMENTO"),
    "financeiro": os.getenv("SETOR_FINANCEIRO", "DEFAULT_FINANCEIRO"),
    "recursos humanos": os.getenv("SETOR_RH", "DEFAULT_RH")
}

#A3SOFT VARS:

A3SOFT_BASE_URL = os.getenv("A3SOFT_BASE_URL")

A3SOFT_LOGIN = os.getenv("A3SOFT_LOGIN")
A3SOFT_SENHA = os.getenv("A3SOFT_SENHA")

A3SOFT_ENDPOINT_LOGIN = os.getenv("A3SOFT_ENDPOINT_LOGIN")
A3SOFT_ENDPOINT_XML = os.getenv("A3SOFT_ENDPOINT_XML")
A3SOFT_ENDPOINT_NF = os.getenv("A3SOFT_ENDPOINT_NF")
A3SOFT_ENDPOINT_TICKET = os.getenv("A3SOFT_ENDPOINT_TICKET")
